name: BlockPerms
main: HenryDM\BlockPerms\Main
api: [4.0.0]
version: 2.2.0
author: HenryDM
description: Advanced plugin to prevent players from placing and breaking specific blocks
website: https://github.com/Henry12960

permissions:
  blockperms.bypass:
    description: ByPass The Block Check
    default: op 
  

