---
# ===================
#     BLOCK PERMS
# ===================
# 1. Advanced plugin to prevent players from placing and breaking specific blocks
# 2. If you see errors, report here: https://github.com/Henry12960/BlockPerms/issues/new
# 3. Plugin made by Henry Thierry [HenryDM] 
# 4. Henry's Website: https://github.com/Henry12960

# ===================
#      GENERAL
# ===================
# 1. You can use 'message' or 'popup' in "messages-type"

messages-type: "popup"
blocks: ["DIAMOND", "EMERALD_BLOCK"]
specific-blocks: ["EMERALD", "IRON"]

block-perms-worlds: ["World", "BlockPerms"]
specific-blocks-worlds: ["Survival", "BlockPerms"]

# ===================
#    PLACE & BREAK
# ===================
# 1. Use {block} to get block name and & to get minecraft color codes.
# 2. If you set 'break-perms' or 'place-perms' to true can disable the function.

place-perms: true
break-perms: true

break-alert-message: true
place-alert-message: true

place-message: "You can't place {block} here!"
break-message: "You can't break {block} here!"

# ===================
#      SPECIFIC
# ===================
# 1. Use {block} to get block name and & to get minecraft color codes.
# 2. INFO: This function if set to true allow player to break or place a specific block!

break-specific-block: false
place-specific-block: false

place-specific-block-message: "-1 {block}"
break-specific-block-message: "+1 {block}"
...