---
#  ____  _            _      _____                        
# |  _ \| |          | |    |  __ \                       
# | |_) | | ___   ___| | __ | |__) |__ _ __ _ __ ___  ___ 
# |  _ <| |/ _ \ / __| |/ / |  ___/ _ \ '__| '_ ` _ \/ __|
# | |_) | | (_) | (__|   <  | |  |  __/ |  | | | | | \__ \
# |____/|_|\___/ \___|_|\_\ |_|   \___|_|  |_| |_| |_|___/
#                                                                                                        
# If you want report bugs: https://github.com/Henry12960/BlockPerms/issues

# ========================
#    General Messages
# ========================

# Warning message if blocked break or placing blocks
alert-message: true

# If you set to true add Place and Break messages
place-message: "§cYou can't put it here!"
break-message: "§cYou can't break it here!"

# ========================
#   Block and World list 
# ========================

anti-break-worlds:
  - Lobby #Example
  - world #Example

anti-place-worlds:
  - Arena #Example
  - MinaPvP #Example
  
blocks:
  - TNT 
  - DIAMOND_BLOCK
  - EMERALD_BLOCK

# ========================
#  Specific block break
# ========================  

allow-specific-break: false
allowed-blocks: 
  - TNT
...